application: hellopyweb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /swfs
  static_dir: swfs
  upload: static/(.*)

- url: /.*
  script: hellopyweb.app

libraries:
- name: jinja2
  version: latest